- update workflows/ci-cd.architect-pipeline.yml

diff --git a/.github/workflows/ci-cd.architect-pipeline.yml b/.github/workflows/ci-cd.architect-pipeline.yml
--- a/.github/workflows/ci-cd.architect-pipeline.yml
+++ b/.github/workflows/ci-cd.architect-pipeline.yml
@@ -15,9 +15,9 @@ on:
         default: 'test-ai-architecture'
         type: string
       requirements_file:
-        description: '📄 Path to the project requirements file'
+        description: '📄 Path to the project requirements file (Ex: sources/requirements/test-requirements.md)'
         required: true
-        default: 'sources/requirements/test-requirements.md'
+        default: ''
         type: string
       phases:
         description: '🔢 Number of phases to split the project'
@@ -100,9 +100,9 @@ on:
         default: 'test-ai-architecture'
         type: string
       requirements_file:
-        description: '📄 Path to the project requirements file'
+        description: '📄 Path to the project requirements file (Ex: sources/requirements/test-requirements.md)'
         required: true
-        default: 'sources/requirements/test-requirements.md'
+        default: ''
         type: string
       phases:
         description: '🔢 Number of phases to split the project'
@@ -189,6 +189,32 @@ jobs:
         uses: actions/checkout@v7
         with:
             fetch-depth: 0
+      
+      # validate parameters
+      - name: 🛡️ Gatekeeper - Validate Parameters
+        env:
+          REQUIREMENTS_FILE: ${{ inputs.requirements_file }}
+        if: success() && inputs.exec_mode != '🚫 None'          # if previous step is successful
+        run: |
+          # check requirements
+          REQUIREMENTS="$REQUIREMENTS_FILE"
+          if [[ -z "$REQUIREMENTS" && -n "$PROJECT_NAME" ]]; then
+            REQUIREMENTS="sources/requirements/$PROJECT_NAME/requirements.md"
+            if [ ! -f "$REQUIREMENTS" ]; then
+              echo "❌ Not found project requirements at: $REQUIREMENTS"
+              exit 1
+            fi
+          
+          elif [ -z "$REQUIREMENTS" ]; then
+            echo "❌ Project requirements file is REQUIRED!"
+            exit 1
+          
+          elif [ ! -f "$REQUIREMENTS" ]; then
+            echo "❌ Not found project requirements at: $REQUIREMENTS"
+            exit 1
+          fi
+          
+          echo "🎉 Found project $PROJECT_NAME requirements at $REQUIREMENTS"
 
       # Step 2: Initialize a clean Python runtime environment
       - name: 🐍 Set up Python Environment
@@ -333,6 +359,12 @@ jobs:
           EXE_DELAY="$EXEC_DELAY"
           if [ -z "$EXE_DELAY" ]; then
             EXE_DELAY=3
+          fi
+          
+          # check requirements
+          REQUIREMENTS="$REQUIREMENTS_FILE"
+          if [[ -z "$REQUIREMENTS" && -n "$PROJECT_NAME" ]]; then
+            REQUIREMENTS="sources/requirements/$PROJECT_NAME/requirements.md"
           fi
           
           echo "⚡ Kicking off AI Agent orchestration..."
